[package]
name = "mo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
tracing = "0"
tracing-subscriber = "0"
termion = "*"
which = "*"
